name: restro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.13.1
  camera: ^0.11.1
  path_provider: ^2.0.15
  image: ^4.5.4
  intl: ^0.20.2
  dio: ^5.8.0+1
  go_router: ^15.1.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  permission_handler: ^11.3.1
  google_mlkit_pose_detection: ^0.11.0
  google_mlkit_commons: ^0.7.0
  json_annotation: ^4.8.1
  image_picker: ^1.0.7
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
    - assets/models/cnn_best.tflite
    - assets/actions.txt
    - assets/scaler.json