// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbucFCHvOdhPB364DNxQidSSnt_lLun4A',
    appId: '1:820287750310:web:c85608d9ae2b18ad62f467',
    messagingSenderId: '820287750310',
    projectId: 'restroapp-flutter',
    authDomain: 'restroapp-flutter.firebaseapp.com',
    storageBucket: 'restroapp-flutter.firebasestorage.app',
    measurementId: 'G-9NJMJN29WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu8u_ZAEZSPM8qUQEtquwAm-EMfMUxxnc',
    appId: '1:820287750310:android:d9935eeaa93db4b062f467',
    messagingSenderId: '820287750310',
    projectId: 'restroapp-flutter',
    storageBucket: 'restroapp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRBFi0jHRT2vpGv1_FYOoiGmmS8XPlADM',
    appId: '1:820287750310:ios:c5e4e5f9d0f47ace62f467',
    messagingSenderId: '820287750310',
    projectId: 'restroapp-flutter',
    storageBucket: 'restroapp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.restro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRBFi0jHRT2vpGv1_FYOoiGmmS8XPlADM',
    appId: '1:820287750310:ios:c5e4e5f9d0f47ace62f467',
    messagingSenderId: '820287750310',
    projectId: 'restroapp-flutter',
    storageBucket: 'restroapp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.restro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbucFCHvOdhPB364DNxQidSSnt_lLun4A',
    appId: '1:820287750310:web:f831afaa706e286762f467',
    messagingSenderId: '820287750310',
    projectId: 'restroapp-flutter',
    authDomain: 'restroapp-flutter.firebaseapp.com',
    storageBucket: 'restroapp-flutter.firebasestorage.app',
    measurementId: 'G-D9QCLVVWTC',
  );
}
